name: Examples

on:
  push:
    branches:
      - 84-models-ci
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm i
      - run: TQDM=0 CACHE_DB=":memory:" DEVICE=WEBGPU deno -A examples/mnist.ts
      - run: TQDM=0 CACHE_DB=":memory:" DEVICE=WEBGPU deno -A examples/simple-matmul.ts
      - run: TQDM=0 CACHE_DB=":memory:" DEVICE=WEBGPU deno -A examples/llama3.ts --prompt=hi --seed=4
      - run: TQDM=0 CACHE_DB=":memory:" DEVICE=WEBGPU deno -A --v8-flags=--max-old-space-size=8192 examples/train-gpt2.ts
