name: Examples

on:
  push:
    branches:
      - 84-models-ci
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: DEVICE=WEBGPU deno -A examples/mnist.ts
