name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"
      - run: npm i

      - name: Publish
        run: deno -A cli/publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Test npm install
        run: |
          VERSION=$(jq -r '.version' dist/package.json)
          mkdir /tmp/node
          cd /tmp/node
          sleep 20
          npm i @jsgrad/jsgrad@$VERSION && npm i ffi-rs
          cp ${{ github.workspace }}/cli/devices-npm.js .
          node devices-npm.js

      - name: Test deno install
        run: |
          VERSION=$(jq -r '.version' dist/package.json)
          mkdir /tmp/deno
          cd /tmp/deno
          sudo apt update -y && sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
          deno i npm:@jsgrad/jsgrad@$VERSION
          cp ${{ github.workspace }}/cli/devices-npm.js .
          deno -A devices-npm.js
