name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Publish
        run: deno task build && cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Test npm install
        run: |
          VERSION=$(jq -r '.version' dist/package.json)
          mkdir /tmp/node
          cd /tmp/node
          sleep 20
          npm i @jsgrad/jsgrad@$VERSION
          cp ${{ github.workspace }}/test/install.test.js .
          node install.test.js
