name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno test -A --parallel --coverage=cov/
      - run: deno coverage --lcov cov/ > cov.lcov
      - uses: codecov/codecov-action@v5
        with:
          file: cov.lcov
          token: ${{ secrets.CODECOV_TOKEN }}