name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          sudo apt update
          sudo apt install -y mesa-vulkan-drivers libvulkan1 libegl1
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: pip install wgpu
      - run: WEBGPU=1 deno test -A --no-check
