name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        runtime: [CLANG, WEBGPU, WASM]

    name: Test (${{ matrix.runtime }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - run: curl -fsSL https://deno.land/install.sh | sh
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install WebGPU deps
        # TODO: add back when runtimes are lazyily imported
        # if: matrix.runtime == 'WEBGPU'
        run: |
          sudo apt update
          sudo apt install -y mesa-vulkan-drivers libvulkan1 libegl1
          pip install wgpu

      - name: Run tests
        run: ${{ matrix.runtime }}=1 TINY_${{ matrix.runtime == 'WASM' && 'CLANG' || matrix.runtime }}=1 deno test -A --no-check --parallel

      - name: Train mnist
        run: ${{ matrix.runtime }}=1 BS=2 STEPS=10 deno -A denograd/models/mnist.ts

